### ISSUE TITLE
Strange inconsistencies between identical requests

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStatsServices#34]
In my batchTest app, a request is made and no watershed is returned.  Workspace folder looks like this:
![image](https://user-images.githubusercontent.com/6529123/30289026-c5e7a41c-96f8-11e7-95a2-b4c0e00775eb.png)

delineation.log: 
```
2017-09-11 17:51:09,755 Initialized
2017-09-11 17:51:09,928 Template spatial ref: NAD_1983_UTM_Zone_18N
2017-09-11 17:51:09,930 Delineation Started
2017-09-11 17:51:10,783 creating workspace environment. D:\ClientData\NY20170911175109754000\NY20170911175109754000.gdb
2017-09-11 17:51:12,744 Starting Delineation
2017-09-11 17:51:17,602 Delineation Error Traceback (most recent call last):
  File "Delineation.py", line 97, in Delineate
    ArcHydroTools.StreamstatsGlobalWatershedDelineation(PourPoint, GW, GWP, xmlPath , "CLEARFEATURES_NO", self.WorkspaceID)
  File "C:\Program Files\ESRI\WaterUtils\ArcHydro\bin\ArcHydroTools.py", line 3530, in StreamstatsGlobalWatershedDelineation
    raise e
ExecuteError: BatchPoint OID = 1: Delineation Error: System.NullReferenceException: Object reference not set to an instance of an object.

   at ESRI.APWR.ApHydro.ArcHydroOp.doGlobalDelineationWorkWorker(IPoint ipPoint, IMap pMap, ApLayers cApLayersLocal, String DataPath, String HucIndex, IFeatureClass fcWatershed, IFeatureClass fcWaterPoint, IFeatureWorkspace ipGlobalWorkspace, Boolean bNeedProjection, Hashtable htParams, String name, String desc, IGPMessages& messages) in C:\Builds\HydroSolutions\10.5_ArcHydro\Sources\ArcHydroTools\src\ApHydro\ArcHydroOp.vb:line 80000
Failed to execute (StreamstatsGlobalWatershedDelineation).
```

BUT if I open the same request in a new tab in Chrome, it works and I see this in the new workspace folder:
![image](https://user-images.githubusercontent.com/6529123/30289070-e9925894-96f8-11e7-8da3-36c40072f8c8.png)

and a successful delineation.log:
```
2017-09-11 17:51:54,224 Initialized
2017-09-11 17:51:54,374 Template spatial ref: NAD_1983_UTM_Zone_18N
2017-09-11 17:51:54,375 Delineation Started
2017-09-11 17:51:55,125 creating workspace environment. D:\ClientData\NY20170911175154224000\NY20170911175154224000.gdb
2017-09-11 17:51:56,809 Starting Delineation
2017-09-11 17:52:09,703 Executing: StreamstatsGlobalWatershedDelineation in_memory\FC D:\ClientData\NY20170911175154224000\NY20170911175154224000.gdb\Layers\GlobalWatershedTemp D:\ClientData\NY20170911175154224000\NY20170911175154224000.gdb\Layers\GlobalWatershedPoint D:\ClientData\NY20170911175154224000\Temp\StreamStatsNY.xml CLEARFEATURES_NO NY20170911175154224000
Start Time: Mon Sep 11 17:51:57 2017
Delineating global watershed for batchpoint 1 of 1.  dt=0.02s
1 global watershed(s) successfully delineated.
Succeeded at Mon Sep 11 17:52:09 2017 (Elapsed Time: 11.66 seconds)
2017-09-11 17:52:10,233 Executing: EliminatePolygonPart D:\ClientData\NY20170911175154224000\NY20170911175154224000.gdb\Layers\GlobalWatershedTemp D:\ClientData\NY20170911175154224000\NY20170911175154224000.gdb\Layers\GlobalWatershed AREA_OR_PERCENT "90 SquareMeters" 1 ANY
Start Time: Mon Sep 11 17:52:09 2017
Succeeded at Mon Sep 11 17:52:10 2017 (Elapsed Time: 0.45 seconds)
2017-09-11 17:52:10,234 Finished
```

Video of strangeness:
http://recordit.co/6MJlF2M8s0

**Comment by HansVraga** [comment]
video was absolutely riveting.
Going to close with the assumption this has been fixed as part of other bug fixes.
